### ISSUE TITLE
Could not find or load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by eguevara2012** [sialan-labs/sigram#33]
Hello!
I trying install Sigram in Ubuntu 12.04 but get this error:

```
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Aborting
```

The folder of Siagram:

```
/opt/sialan/sigram/qtplugins/platforms/libqxcb.so
```

Runnig command ldd:

```
/opt/sialan/sigram/qtplugins/platforms$ ldd libqxcb.so
```

The output:

```
libQt5DBus.so.5 => not found
libQt5Gui.so.5 => not found
libQt5Core.so.5 => not found
```

What plugin is missing?
Thanks!

**Comment by Dodoheimer** [comment]
Hi,

im using Xubuntu 14.04 32bit and i have the same error:

"This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Abgebrochen (Speicherabzug geschrieben)"

I hope you can help by this problem :)

**Comment by luisalvarado** [comment]
This is happening in both, 32 Bit and 64 Bit versions of Ubuntu. I have installed all QT libraries related to xcb just in case Ubuntu did not bring them by default and still the bug is there. I also used ldd and even when it shows them as available:

```
libQt5DBus.so.5 => /usr/lib/i386-linux-gnu/libQt5DBus.so.5 (0xb71d8000)
libQt5Gui.so.5 => /usr/lib/i386-linux-gnu/libQt5Gui.so.5 (0xb6d7f000)
libQt5Core.so.5 => /usr/lib/i386-linux-gnu/libQt5Core.so.5 (0xb68e9000)
```

The app does not work. After adding the "-r" parameter I got this:

undefined symbol: _ZN20QPlatformIntegration16openGLModuleTypeEv (./libqxcb.so)
undefined symbol: _ZNK15QPlatformWindow14normalGeometryEv   (./libqxcb.so)
undefined symbol: _ZN15QPlatformWindow17invalidateSurfaceEv (./libqxcb.so)
undefined symbol: _ZNK21QPlatformBackingStore9toTextureERK7QRegionP5QSize   (./libqxcb.so)
undefined symbol: _ZN21QPlatformFontDatabase14populateFamilyERK7QString (./libqxcb.so)
undefined symbol: _ZN21QPlatformFontDatabase10invalidateEv  (./libqxcb.so)
undefined symbol: _ZNK11QFontEngine16getSfntTableDataEjPhPj (./libqxcb.so)
undefined symbol: _ZNK16QFontEngineMulti10glyphIndexEj  (./libqxcb.so)
undefined symbol: _ZNK16QFontEngineMulti9canRenderEPK5QChari    (./libqxcb.so)
undefined symbol: _ZNK14QPlatformTheme18standardButtonTextEi    (./libqxcb.so)
undefined symbol: _ZNK11QFontEngine9canRenderEPK5QChari (./libqxcb.so)
undefined symbol: _ZN14QSurfaceFormat9setOptionENS_12FormatOptionEb (./libqxcb.so)
undefined symbol: _ZN21QAbstractConcatenable14appendLatin1ToEPKciP5QChar    (./libqxcb.so)
undefined symbol: _ZN14QSurfaceFormat10setOptionsE6QFlagsINS_12FormatOptionEE   (./libqxcb.so)
undefined symbol: _ZNK14QSurfaceFormat10testOptionENS_12FormatOptionE   (./libqxcb.so)
undefined symbol: _ZN21QPlatformBackingStore15composeAndFlushEP7QWindowRK7QRegionRK6QPointP20QPlatformTextureListP14QOpenGLContext  (./libqxcb.so)
undefined symbol: _ZNK14QPlatformTheme18standardButtonTextEi    (./libqxcb.so)
undefined symbol: _ZN11QFontEngineC2ENS_4TypeE  (./libqxcb.so)
undefined symbol: _ZNK14QSurfaceFormat12swapIntervalEv  (./libqxcb.so)
undefined symbol: _ZN7QPixmap16fromImageInPlaceER6QImage6QFlagsIN2Qt19ImageConversionFlagEE (./libqxcb.so)

So they are several issues related with the libqxcb library.

If you use the "Linux" version from their site, it will work after executing the ./Sigram app. The whole issue is with the Ubuntu packages that are shown there.

**Comment by realbardia** [comment]
Please set LD_LIBRARY_PATH env to "/opt/sialan/sigram/libs/" and run it again. I think sigram can't find Qt5.3 libraries that are in the /opt/sialan/sigram/libs/.
export LD_LIBRARY_PATH="/opt/sialan/sigram/libs/"

**Comment by luisalvarado** [comment]
That worked. Should be easily solvable on the next update.

**Comment by eguevara2012** [comment]
Hi!
According to Ubuntu documentation(https://help.ubuntu.com/community/EnvironmentVariables#A.2BAC8-etc.2BAC8-environment):

```
Since Ubuntu 9.04 Jaunty Jackalope, LD_LIBRARY_PATH cannot be set in $HOME/.profile, /etc/profile, nor /etc/environment files. You must use /etc/ld.so.conf.d/*.conf configuration files. See Launchpad bug #366728 for more information. 
```

I create a  /etc/ld.so.conf.d/sigram.conf file and put:

```
/opt/sialan/sigram/libs/
```

Then run:

```
sudo ldconfig -v
```

The output:

```
    /opt/sialan/sigram/libs:
libQt5Core.so.5 -> libQt5Core.so.5
libqgsttools_p.so.1 -> libqgsttools_p.so.1
libicuuc.so.52 -> libicuuc.so.52
libQt5PrintSupport.so.5 -> libQt5PrintSupport.so.5
libicutest.so.52 -> libicutest.so.52
libQt5Widgets.so.5 -> libQt5Widgets.so.5
libicudata.so.52 -> libicudata.so.52
libiculx.so.52 -> libiculx.so.52
libicuio.so.52 -> libicuio.so.52
libicutu.so.52 -> libicutu.so.52
libicui18n.so.52 -> libicui18n.so.52
libQt5Svg.so.5 -> libQt5Svg.so.5
libQt5Gui.so.5 -> libQt5Gui.so.5
libEnginio.so.1 -> libEnginio.so.1
libQt5MultimediaQuick_p.so.5 -> libQt5MultimediaQuick_p.so.5
libicule.so.52 -> libicule.so.52
libQt5Sql.so.5 -> libQt5Sql.so.5
libcrypto.so.1.0.0 -> libcrypto.so.1.0.0
libQt5Multimedia.so.5 -> libQt5Multimedia.so.5
libQt5Qml.so.5 -> libQt5Qml.so.5
libQt5Network.so.5 -> libQt5Network.so.5
libQt5Quick.so.5 -> libQt5Quick.so.5
libQt5DBus.so.5 -> libQt5DBus.so.5
```

That's fine, but sigram still not run.

```
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Aborting
```

Any idea?

**Comment by realbardia** [comment]
I added this file to source:
https://github.com/sialan-labs/sigram/blob/master/Sigram/run
It's a shell-script file that run sigram with LD_LIBRARY_PATH .

**Comment by realbardia** [comment]
Fixed in the last binary packages
