### ISSUE TITLE
Connect through proxy [Ubuntu 14.04 x64]

### ISSUE THREAD

**Issue by vrcca** [sialan-labs/sigram#45]
Hello,

I'm trying to use the application behind the company's proxy, but the application won't go past the first screen. It keeps "Connecting..." ad eternum.

Is there a way to connect through proxy?

Thanks!

**Comment by realbardia** [comment]
Hi...
No... There is no standard way to connect trough proxy currently.
We will porting from telegram_cli to new libraries (libqtelegram). libqtelegram support proxy :)

**Comment by pntkrtr** [comment]
Hello, I installed sigram 0.7.0 working in debian jessie and I am very interested in the connection via proxy (the future port to new librarie llbqtelegram) because the program starts, but goes into a closed loop that fails. 
Meanwhile I will continue using telegram through wine. Thank you very much for your work.
